Repository The-BizWiz/biz-wiz-frontend, pull requests merged in 2021-04, with the labels that each got.

#18 Fixes home page redirect and other router errors
  package-lock.json
  src/App.js
  src/components/SignUp.js
  src/lib/customHooks.js
  src/services/auth.js
  src/services/config.js
Labels: bug

#21 Successfully registers new business accounts
  src/components/SignUp.js
  src/services/auth.js
  src/services/config.js
Labels: bug, enhancement

#42 Dev
  src/components/Home.js
  src/components/NavbarNew.js
Labels: enhancement

#48 Full rework of login page adding several features
  src/components/Home.js
  src/components/NavbarNew.js
  src/components/SignIn.js
Labels: enhancement

#51 fixes search page redirect and removes icon from search bar
  src/App.js
  src/components/Home.js
  src/components/NavbarNew.js
  src/components/SignIn.js
Labels: bug

#61 creation of business profile page and rework create post page
  src/App.js
  src/components/DrawerForProfile.js
  src/components/NavbarNew.js
  src/components/Post.js
  src/components/PostCards.js
  src/components/ProfilePage.js
  src/components/SignIn.js
Labels: enhancement

#62 Dev
  package-lock.json
  src/components/ProfilePage.js
  src/components/SignIn.js
  src/services/auth.js
Labels: enhancement

#67 adds functionality to trash icon to delete a businesses post and displays comments on a post
  package-lock.json
  package.json
  src/components/Post.js
  src/components/PostCards.js
  src/components/ProfilePage.js
Labels: enhancement

#75 Dev
  src/components/PostCards.js
  src/components/ProfilePage.js
Labels: bug

#91 Adds functionality to account page
  src/components/Account.js
  src/components/PostCards.js
  src/components/ProfilePage.js
Labels: enhancement

#92 styles account page and refreshes data on save
  src/components/Account.js
Labels: enhancement

#95 styles profile page and sign up page
  src/components/Account.js
  src/components/DrawerForProfile.js
  src/components/Home.js
  src/components/NavbarLoggedIn.js
  src/components/NavbarNew.js
  src/components/Post.js
  src/components/PostCards.js
  src/components/ProfilePage.js
  src/components/SignIn.js
  src/components/SignUp.js
  src/services/auth.js
Labels: enhancement

#104 adds transition from material ui
  src/components/PostCards.js
  src/components/ProfilePage.js
  src/components/SearchContent.js
Labels: enhancement
